

import util
		
print "/* THIS FILE WAS AUTOGENERATED FROM explicit_goal.cpp.py */"
print "#include <casper/kernel/spexpr/expr.h>"
print "namespace Casper {"
print "namespace Detail {"

util.printGoal(False)

print "}"
print "}"
