

import util
		
print "/* THIS FILE WAS AUTOGENERATED FROM explicit_ref.h.py */"
print "#include <casper/kernel/spexpr/expr.h>"
print "namespace Casper {"
print "namespace Detail {"

util.printRef(True)

print "}"
print "}"
