

import util
		
print "/* THIS FILE WAS AUTOGENERATED FROM explicit_ref.h.py */"
print "#include <casper/kernel/spexpr/expr_wrapper.h>"
print "namespace Casper {"
util.printRel(True)
print "namespace Detail {"
util.printRef(True)
util.printGoal(True)
util.printExprWrapper(True)

print "}"
print "}"
