

import util

print "/* THIS FILE WAS AUTOGENERATED FROM post.h.py */"
#print "#include <casper/kernel/spexpr/expr.h>"
print "namespace Casper {"
print "template<class> struct Expr;"
print "namespace CP {"
util.printPost(True,"Val")
print "}"
print "}"
