

import util

print "/* THIS FILE WAS AUTOGENERATED FROM post.h.py */"
print "namespace Casper {"
print "template<class> struct Expr;"
print "namespace CP {"
util.printPost(True,"Dom")
print "}"
print "}"
