

import os
import sys

libPath = os.path.abspath('casper/cp/spexpr')
sys.path.append(libPath)

import cputil
import util


print "/* THIS FILE WAS AUTOGENERATED FROM explicit.cpp.py */"
print "#include <casper/cp/spexpr/expr.h>"
print "namespace Casper {"
print "namespace Detail {"
util.printViews(False)
util.printPost2(False)
util.printRef(False)
cputil.printExprWrapper(False,"int")
util.printExprWrapper(False)
print "}"

print "}"
