

import util

print "/* THIS FILE WAS AUTOGENERATED FROM post.cpp.py */"
print "#include <casper/kernel/spexpr/expr.h>"
print "namespace Casper {"
print "namespace CP {"
util.printPost(False,"Bnd")
print "}"
print "}"
