

import util

print "/* THIS FILE WAS AUTOGENERATED FROM explicit.h.py */"
print "#include <casper/cp/spexpr/expr.h>"
print "namespace Casper {"
print "namespace Detail {"
util.printViews(True)
util.printPost2(True)
util.printRef(True)
print "}"


print "}"
