/************************************************************************** *   This file is part of CaSPER (http://proteina.di.fct.unl.pt/casper).   *
*
 *                                                                         *
 *   Copyright:                                                            *
 *   2005-2008 - Marco Correia <marco.v.correia@gmail.com>                 *
 *                                                                         *
 *   Licensed under the Apache License, Version 2.0 (the "License");       * 
 *   you may not use this file except in compliance with the License.      * 
 *   You may obtain a copy of the License at                               * 
 *            http://www.apache.org/licenses/LICENSE-2.0                   * 
 *   Unless required by applicable law or agreed to in writing, software   * 
 *   distributed under the License is distributed on an                    * 
 *   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,          * 
 *   either express or implied.                                            * 
 *   See the License for the specific language governing permissions and   * 
 *   limitations under the License.                                        *
 \*************************************************************************/
/************************************************************************** *   This file is part of CaSPER (http://proteina.di.fct.unl.pt/casper).   *
*
 *                                                                         *
 *   Copyright:                                                            *
 *   2005-2008 - Marco Correia <marco.v.correia@gmail.com>                 *
 *                                                                         *
 *   Licensed under the Apache License, Version 2.0 (the "License");       * 
 *   you may not use this file except in compliance with the License.      * 
 *   You may obtain a copy of the License at                               * 
 *            http://www.apache.org/licenses/LICENSE-2.0                   * 
 *   Unless required by applicable law or agreed to in writing, software   * 
 *   distributed under the License is distributed on an                    * 
 *   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,          * 
 *   either express or implied.                                            * 
 *   See the License for the specific language governing permissions and   * 
 *   limitations under the License.                                        *
 \*************************************************************************/
// --- RELATIONS (Compile time expressions) ---
/** Symmetric unary operator. */ template< class T1, Int dims > inline Rel1<Sym,Array< T1,dims> > operator-(const Array< T1,dims>& rh) { return Rel1<Sym,Array< T1,dims> >(rh);} /** Negation unary operator. */ template< class T1, Int dims > inline Rel1<Not,Array< T1,dims> > operator!(const Array< T1,dims>& rh) { return Rel1<Not,Array< T1,dims> >(rh);} /** Absolute value unary operator. */ template< class T1, Int dims > inline Rel1<Abs,Array< T1,dims> > abs(const Array< T1,dims>& rh) { return Rel1<Abs,Array< T1,dims> >(rh);} /** Min value (from a sequence) unary operator. */ template< class T1, Int dims > inline Rel1<Min,Array< T1,dims> > min(const Array< T1,dims>& rh) { return Rel1<Min,Array< T1,dims> >(rh);} /** Max value (from a sequence) unary operator. */ template< class T1, Int dims > inline Rel1<Max,Array< T1,dims> > max(const Array< T1,dims>& rh) { return Rel1<Max,Array< T1,dims> >(rh);}
/** Equal binary operator. */ template< class T1, Int dims, class T > inline Rel2<Equal,Array< T1,dims>,T > operator==(const Array< T1,dims>& lh, const T& rh) { return Rel2<Equal,Array< T1,dims>,T >(lh,rh); } /** Greater or equal binary operator. */ template< class T1, Int dims, class T > inline Rel2<GreaterEqual,Array< T1,dims>,T > operator>=(const Array< T1,dims>& lh, const T& rh) { return Rel2<GreaterEqual,Array< T1,dims>,T >(lh,rh); } /** Less or equal binary operator. */ template< class T1, Int dims, class T > inline Rel2<LessEqual,Array< T1,dims>,T > operator<=(const Array< T1,dims>& lh, const T& rh) { return Rel2<LessEqual,Array< T1,dims>,T >(lh,rh); } /** Distinct binary operator. */ template< class T1, Int dims, class T > inline Rel2<Distinct,Array< T1,dims>,T > operator!=(const Array< T1,dims>& lh, const T& rh) { return Rel2<Distinct,Array< T1,dims>,T >(lh,rh); } /** Greater than binary operator. */ template< class T1, Int dims, class T > inline Rel2<Greater,Array< T1,dims>,T > operator>(const Array< T1,dims>& lh, const T& rh) { return Rel2<Greater,Array< T1,dims>,T >(lh,rh); } /** Less than binary operator. */ template< class T1, Int dims, class T > inline Rel2<Less,Array< T1,dims>,T > operator<(const Array< T1,dims>& lh, const T& rh) { return Rel2<Less,Array< T1,dims>,T >(lh,rh); } /** Addition binary operator. */ template< class T1, Int dims, class T > inline Rel2<Add,Array< T1,dims>,T > operator+(const Array< T1,dims>& lh, const T& rh) { return Rel2<Add,Array< T1,dims>,T >(lh,rh); } /** Subtraction binary operator. */ template< class T1, Int dims, class T > inline Rel2<Sub,Array< T1,dims>,T > operator-(const Array< T1,dims>& lh, const T& rh) { return Rel2<Sub,Array< T1,dims>,T >(lh,rh); } /** Multiplication binary operator. */ template< class T1, Int dims, class T > inline Rel2<Mul,Array< T1,dims>,T > operator*(const Array< T1,dims>& lh, const T& rh) { return Rel2<Mul,Array< T1,dims>,T >(lh,rh); } /** Division binary operator. */ template< class T1, Int dims, class T > inline Rel2<Div,Array< T1,dims>,T > operator/(const Array< T1,dims>& lh, const T& rh) { return Rel2<Div,Array< T1,dims>,T >(lh,rh); } /** Logical AND binary operator. */ template< class T1, Int dims, class T > inline Rel2<And,Array< T1,dims>,T > operator&&(const Array< T1,dims>& lh, const T& rh) { return Rel2<And,Array< T1,dims>,T >(lh,rh); } /** Logical OR operator. */ template< class T1, Int dims, class T > inline Rel2<Or,Array< T1,dims>,T > operator||(const Array< T1,dims>& lh, const T& rh) { return Rel2<Or,Array< T1,dims>,T >(lh,rh); }
/** Equal binary operator. */ template< class T1, Int dims > inline Rel2<Equal,Int,Array< T1,dims> > operator==(const Int& lh, const Array< T1,dims>& rh) { return Rel2<Equal,Int,Array< T1,dims> >(lh,rh); } /** Greater or equal binary operator. */ template< class T1, Int dims > inline Rel2<GreaterEqual,Int,Array< T1,dims> > operator>=(const Int& lh, const Array< T1,dims>& rh) { return Rel2<GreaterEqual,Int,Array< T1,dims> >(lh,rh); } /** Less or equal binary operator. */ template< class T1, Int dims > inline Rel2<LessEqual,Int,Array< T1,dims> > operator<=(const Int& lh, const Array< T1,dims>& rh) { return Rel2<LessEqual,Int,Array< T1,dims> >(lh,rh); } /** Distinct binary operator. */ template< class T1, Int dims > inline Rel2<Distinct,Int,Array< T1,dims> > operator!=(const Int& lh, const Array< T1,dims>& rh) { return Rel2<Distinct,Int,Array< T1,dims> >(lh,rh); } /** Greater than binary operator. */ template< class T1, Int dims > inline Rel2<Greater,Int,Array< T1,dims> > operator>(const Int& lh, const Array< T1,dims>& rh) { return Rel2<Greater,Int,Array< T1,dims> >(lh,rh); } /** Less than binary operator. */ template< class T1, Int dims > inline Rel2<Less,Int,Array< T1,dims> > operator<(const Int& lh, const Array< T1,dims>& rh) { return Rel2<Less,Int,Array< T1,dims> >(lh,rh); } /** Addition binary operator. */ template< class T1, Int dims > inline Rel2<Add,Int,Array< T1,dims> > operator+(const Int& lh, const Array< T1,dims>& rh) { return Rel2<Add,Int,Array< T1,dims> >(lh,rh); } /** Subtraction binary operator. */ template< class T1, Int dims > inline Rel2<Sub,Int,Array< T1,dims> > operator-(const Int& lh, const Array< T1,dims>& rh) { return Rel2<Sub,Int,Array< T1,dims> >(lh,rh); } /** Multiplication binary operator. */ template< class T1, Int dims > inline Rel2<Mul,Int,Array< T1,dims> > operator*(const Int& lh, const Array< T1,dims>& rh) { return Rel2<Mul,Int,Array< T1,dims> >(lh,rh); } /** Division binary operator. */ template< class T1, Int dims > inline Rel2<Div,Int,Array< T1,dims> > operator/(const Int& lh, const Array< T1,dims>& rh) { return Rel2<Div,Int,Array< T1,dims> >(lh,rh); } /** Logical AND binary operator. */ template< class T1, Int dims > inline Rel2<And,Int,Array< T1,dims> > operator&&(const Int& lh, const Array< T1,dims>& rh) { return Rel2<And,Int,Array< T1,dims> >(lh,rh); } /** Logical OR operator. */ template< class T1, Int dims > inline Rel2<Or,Int,Array< T1,dims> > operator||(const Int& lh, const Array< T1,dims>& rh) { return Rel2<Or,Int,Array< T1,dims> >(lh,rh); }
