

import util

print "/* THIS FILE WAS AUTOGENERATED FROM post.h.py */"
print "#include <casper/kernel/spexpr/expr.h>"
print "namespace Casper {"
print "namespace CP {"
util.printPost(True)
print "}"
print "}"
