

import util

print "/* THIS FILE WAS AUTOGENERATED FROM ref.cpp.py */"
print "#include <casper/kernel/spexpr/expr.h>"
print "namespace Casper {"
print "namespace Detail {"
util.printRef(False)
print "}"
print "}"
