/* THIS FILE WAS AUTOGENERATED FROM view.h.py */
#include <casper/kernel/spexpr/expr.h>
namespace Casper {
namespace Detail {
extern template struct Create<CP::Var<Casper::IntSet>,CP::DomExpr<Casper::IntSet>>;
extern template struct Create<CP::Var<Casper::BoolSet>,CP::DomExpr<Casper::BoolSet>>;
}
}
