

import util

print "/* THIS FILE WAS AUTOGENERATED FROM view.h.py */"
print "#include <casper/kernel/spexpr/expr.h>"
print "namespace Casper {"
print "namespace Detail {"
util.printViews(True)
print "}"
print "}"
