

import util

print "/* THIS FILE WAS AUTOGENERATED FROM view.h.py */"
print "#include <casper/cp/spexpr/expr.h>"
print "namespace Casper {"
util.printRel(False)
print "namespace Detail {"
util.printViews(False)
util.printExprWrapper(False)
util.printPost2(False)
util.printRef(False)
print "}"

print "}"
